service: session5-body-pose

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-south-1
  timeout: 60
  # environment:
  #   S3_BUCKET : session5-body-pose
  #   MODEL_PATH : simple_pose_estimation_quantized.onnx
  iamRoleStatements:
     - Effect: "Allow"
       Action: 
          - "s3:getObject"
          - "s3:PutObject"
          - "s3:PutObjectAcl"
          - "s3:GetObjectAcl"
       Resource: arn:aws:s3:::session5-body-pose/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy: 
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  estimate_pose:
    handler: handler.estimate_pose
    memorySize: 3008
    timeout: 60
    events: 
        - http:
                path: estimate
                method: post
                cors: true

plugins:
  - serverless-python-requirements
